#!/bin/bash

if [ ! -d "/media/veracrypt1/storage" ]; then
	sudo veracrypt --password=91263l0ngXst4nd1ng3mul04d3rcitizenFOUR7445477Asusvw195n! --mount /dev/sda5
fi

#if [ ! -d "/home/void/Documents/music/Playlists" ]; then
#	sudo mount -t cifs -o user=admin,pass=Asusvw195n\!,domain=WORKSPACE //192.168.0.242/storage/music /home/void/Documents/music
#fi

if [ ! -d "/home/void/Documents/storage/video" ]; then
	sudo mount -t cifs -o user=admin,pass=Asusvw195n\!,domain=WORKSPACE,uid=void,gid=wheel //192.168.0.242/storage/ /home/void/Documents/storage
fi
