#!/bin/bash
case $BLOCK_BUTTON in
    1) $TERMINAL -e sudo pacman -Syu && pacman -Qu | wc -l > /home/void/.scripts/.pacupgrade && pkill -RTMIN+8 i3blocks ;;
esac

pacman -Qu | wc -l | sed -e '/^0$/d' > /home/void/.scripts/.pacupgrade && pkill -RTMIN+8 i3blocks

cat /home/void/.scripts/.pacupgrade | sed -e "/^$/d"
