#!/bin/bash
### This is only if your location isn't automatically detected,$
location="Aachen Germany"

[[ "$location" != "" ]] && location="~${location// /+}"

curl -s wttr.in/$location > ~/.weatherreport

cat ~/.weatherreport && read
