#!/bin/bash

# Increase key speed via a rate change
xset r rate 300 50

# Map the caps lock key to super
#setxkbmap -layout us -option caps:super
setxkbmap -option caps:super

# But when it is pressed only once, treat it as escape.
xcape -e 'Super_L=Escape'

#xmodmap -e "clear lock" #disable caps lock switch
#xmodmap -e "keysym Caps_Lock = Escape" #set caps_lock as escape
