#!/bin/bash

read TPdevice <<< $( xinput | sed -nre '/Touchpad/s/.*id=([0-9]*).*/\1/p' )

read TapProp <<< $( xinput list-props $TPdevice | sed -nre '/Tapping En/s/.*d \(([0-9]*).*/\1/p' )
read MidProp <<< $( xinput list-props $TPdevice | sed -nre '/Emulation/s/.*d \(([0-9]*).*/\1/p' )

xinput set-prop	$TPdevice $TapProp 1
xinput set-prop	$TPdevice $MidProp 1
